version: '2'

services:
 andes:  
  image: mongo:3.6
  container_name: andes
  volumes:
    - vandes:/data/db
  ports:
    - "27017:27017"
 andes_kibana:
    image: blacktop/kibana:5.5  
    container_name: andes_kibana
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: andes_kibana
      SERVER_PORT: 5601
      SEVER_HOST: localhost
      ELASTICSEARCH_URL: http://andes_elastic:9200
 andes_elasticsearch:
    image: blacktop/elasticsearch:5.5 
    container_name: andes_elastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - velastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200" 
volumes:
  vandes:
  velastic:
    driver: local
